import localFont from "next/font/local";
import "./globals.css";
import { CartProvider } from "./(site)/components/Cart/CartProvider";
import { UserProvider } from "./(site)/components/Login/UserProvider";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={"dark:bg-dark dark:text-white" + `${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>

        <CartProvider> {/* Wrap children with CartProvider */}
          {children}
        </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
