version: '3.8'
services:
  database:
    image: postgres:14
    environment:
      POSTGRES_DB: alledrogo
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
