INSERT INTO reviews (product_id, user_id, rating, comment, review_date)
VALUES
    (1, 1, 5, 'Great product! Highly recommend.', CURRENT_TIMESTAMP),
    (1, 2, 4, 'Good product, but could be a bit cheaper.', CURRENT_TIMESTAMP),
    (1, 3, 3, 'Average product, I expected something better.', CURRENT_TIMESTAMP),
    (1, 1, 5, 'Amazing! I would buy it again.', CURRENT_TIMESTAMP),
    (2, 1, 4, 'The product quality is very good.', CURRENT_TIMESTAMP),
    (2, 2, 3, 'A bit too expensive for what it offers.', CURRENT_TIMESTAMP),
    (2, 2, 2, 'The product does not meet my expectations.', CURRENT_TIMESTAMP),
    (2, 3, 5, 'Great, everything matches the description.', CURRENT_TIMESTAMP),
    (3, 2, 5, 'The best product in its category.', CURRENT_TIMESTAMP),
    (3, 3, 4, 'Not the worst, but not perfect.', CURRENT_TIMESTAMP),
    (3, 1, 5, 'Definitely worth buying.', CURRENT_TIMESTAMP),
    (3, 2, 3, 'I rate the product 3, it’s not bad.', CURRENT_TIMESTAMP),
    (4, 1, 5, 'Great product, worth its price.', CURRENT_TIMESTAMP),
    (4, 3, 4, 'Very good, but has a few minor flaws.', CURRENT_TIMESTAMP),
    (4, 1, 2, 'Did not meet my expectations.', CURRENT_TIMESTAMP),
    (4, 2, 5, 'I recommend it to everyone; the product is excellent.', CURRENT_TIMESTAMP),
    (5, 1, 3, 'Average, I thought it would be better.', CURRENT_TIMESTAMP),
    (5, 3, 5, 'Really great product.', CURRENT_TIMESTAMP),
    (5, 2, 4, 'Good product, but could be cheaper.', CURRENT_TIMESTAMP),
    (5, 1, 5, 'No need to hesitate, worth buying.', CURRENT_TIMESTAMP);